### ISSUE TITLE
API key Exposed.

### ISSUE THREAD

**Issue by SameepHedaoo** [raun1997/Weather-App-CustomTkinter-#1]
Hello,
I noticed your api key is exposed in main.py file under src, as you can see in the below attached image:

![image](https://user-images.githubusercontent.com/91476638/179358540-c336186e-88ea-4451-956e-86395100e9e2.png)

I would suggest to make an .env file and save the API_Key there and then use it in the main.py file by using config() function of python-decouple library. As shown in the below image:

![image](https://user-images.githubusercontent.com/91476638/179358622-10c4e5cd-39aa-4203-8e92-285b05f2e1c9.png)

**Comment by dedire229** [comment]
Yeah, I was just trying out the "Git: Push" option in Atom IDE. I had no plans of publishing the repo. Nevertheless, I should have been cautious.

**Comment by SameepHedaoo** [comment]
Okay sir no issue. :)

**Comment by dedire229** [comment]
But thanks though. I really overlooked the part.

**Comment by dedire229** [comment]
I added the .env file
